vpn(1) [""["vpn-1.0.0"]]

# NAME

vpn - A TUI wg-quick interface.

# SYNOPSIS

vpn [ on | up | off | down ]

# DESCRIPTION

VPN has two usage modes. An interactive TUI interface and a CLI interface for
quickly connecting or disconnecting from your most recent config. Both modes
read a list of configured servers in /etc/wireguard.

# AUTHORS

"Maintained" by Dakota Walsh <kota at nilsu.org>.
Up-to-date sources can be found at https://git.sr.ht/~kota/vpn/
